import { imageDomainUrl } from 'shared/constants/Assets';

// Define the type for reminders items
interface RemindersItem {
  color: string;
  title: string;
  description: string;
  maxWidth: string;
  img: string;
  height: number;
  width: number;
  class: string;
}

// Define the reminders contents
const REMINDERS_CONTENTS: RemindersItem[] = [
  {
    color: 'text-[#00C0C5]',
    title: 'Drink plenty of water',
    description: 'Enjoy water and stay hydrated throughout the day.',
    maxWidth: 'max-w-[218px]',
    img: `${imageDomainUrl}/WellnessHub/drink-water.svg`,
    height: 119,
    width: 119,
    class: 'mr-[-8px] right-0 top-[-11px]',
  },
  {
    color: 'text-[#B38DB2]',
    title: 'Move your body',
    description: 'Get some form of physical activity, even a short walk.',
    maxWidth: 'max-w-[214px]',
    img: `${imageDomainUrl}/WellnessHub/move-your-body.svg`,
    height: 119,
    width: 119,
    class: 'mr-[-8px] right-0 top-[-11px]',
  },
  {
    color: 'text-[#9AC17E]',
    title: 'Practice gratitude',
    description: 'Reflect on something you are grateful for.',
    maxWidth: 'max-w-[180px]',
    img: `${imageDomainUrl}/WellnessHub/practice-gratitude.svg`,
    height: 99,
    width: 99,
    class: 'mr-[2px] right-0 top-[-6px]',
  },
  {
    color: 'text-[#539ED9]',
    title: 'Eat nourishing foods',
    description: 'Fuel your body with balanced, healthy meals.',
    maxWidth: 'max-w-[166px]',
    img: `${imageDomainUrl}/WellnessHub/nourishing-foods.svg`,
    height: 119,
    width: 119,
    class: 'mr-[-7px] right-0 top-[-10px]',
  },
  {
    color: 'text-[#D96D99]',
    title: 'Take deep breaths',
    description: 'Pause and breathe deeply to reduce stress and stay calm.',
    maxWidth: 'max-w-[210px]',
    img: `${imageDomainUrl}/WellnessHub/take-breaths.svg`,
    height: 119,
    width: 119,
    class: 'mr-[-7px] right-0 top-[-11px]',
  },
  {
    color: 'text-[#00C0C5]',
    title: 'Get enough sleep',
    description: "Prioritize a full night's rest to recharge your body and mind.",
    maxWidth: 'max-w-[214px]',
    img: `${imageDomainUrl}/WellnessHub/enough-sleep.svg`,
    height: 119,
    width: 119,
    class: 'mr-[-1px] right-0 top-[-10px]',
  },
  {
    color: 'text-[#B38DB2]',
    title: 'Set daily intentions',
    description: 'Start your day by setting positive intentions or goals.',
    maxWidth: 'max-w-[178px]',
    img: `${imageDomainUrl}/WellnessHub/set-intentions.svg`,
    height: 119,
    width: 119,
    class: 'mr-[-3px] right-0 top-[-14px]',
  },
  {
    color: 'text-[#9AC17E]',
    title: 'Stay connected',
    description: 'Reach out to a friend or loved one for a quick check-in.',
    maxWidth: 'max-w-[195px]',
    img: `${imageDomainUrl}/WellnessHub/stay-connected.svg`,
    height: 119,
    width: 119,
    class: 'mr-[-4px] right-0 top-[-7px]',
  },
  {
    color: 'text-[#539ED9]',
    title: 'Limit screen time',
    description: 'Take breaks from screens to rest your eyes and mind.',
    maxWidth: 'max-w-[178px]',
    img: `${imageDomainUrl}/WellnessHub/limitscreen-time.svg`,
    height: 93,
    width: 93,
    class: 'mr-[1px] right-0 top-[-8px]',
  },
  {
    color: 'text-[#D96D99]',
    title: 'Self-compassion',
    description: 'Be kind to yourself, especially on tough days.',
    maxWidth: 'max-w-[179px]',
    img: `${imageDomainUrl}/WellnessHub/practice-compassion.svg`,
    height: 119,
    width: 119,
    class: 'mr-[0px] right-0 top-[-4px]',
  },
  {
    color: 'text-[#00C0C5]',
    title: 'Take breaks',
    description: 'Step away from work or tasks to refresh your mind and body.',
    maxWidth: 'max-w-[203px]',
    img: `${imageDomainUrl}/WellnessHub/take-breaks.svg`,
    height: 119,
    width: 119,
    class: 'mr-[-2px] right-0 top-[-4px]',
  },
  {
    color: 'text-[#B38DB2]',
    title: 'Laugh and smile',
    description: 'Find moments of joy and humor throughout your day.',
    maxWidth: 'max-w-[183px]',
    img: `${imageDomainUrl}/WellnessHub/laugh-and-smile.svg`,
    height: 95,
    width: 95,
    class: 'mr-[6px] right-0 top-[-4px]',
  },
  {
    color: 'text-[#539ED9]',
    title: 'Declutter your space',
    description: 'Organize to create a more peaceful environment.',
    maxWidth: 'max-w-[186px]',
    img: `${imageDomainUrl}/WellnessHub/declutter-space.svg`,
    height: 119,
    width: 119,
    class: 'mt-[2px] mr-[-7px] right-0 top-[-11px]',
  },
  {
    color: 'text-[#9AC17E]',
    title: 'Spend time in nature',
    description: 'Get outside and take a moment to appreciate nature.',
    maxWidth: 'max-w-[200px]',
    img: `${imageDomainUrl}/WellnessHub/spend-time.svg`,
    height: 119,
    width: 119,
    class: 'mr-[-6px] right-0 top-[-11px]',
  },
  {
    color: 'text-[#D96D99]',
    title: 'Focus on the present',
    description: 'Practice mindfulness and stay present in the moment.',
    maxWidth: 'max-w-[185px]',
    img: `${imageDomainUrl}/WellnessHub/focus-present.svg`,
    height: 107,
    width: 107,
    class: 'mr-[5px] right-0 top-[-5px]',
  },
  {
    color: 'text-[#00C0C5]',
    title: 'Celebrate small wins',
    description: 'Acknowledge and appreciate the little victories.',
    maxWidth: 'max-w-[191px]',
    img: `${imageDomainUrl}/WellnessHub/celebrate-wins.svg`,
    height: 95,
    width: 95,
    class: 'mr-[5px] right-0 top-[-4px]',
  },
  {
    color: 'text-[#B38DB2]',
    title: 'Stay curious',
    description: 'Learn something new or explore a different view.',
    maxWidth: 'max-w-[194px]',
    img: `${imageDomainUrl}/WellnessHub/stay-curious.svg`,
    height: 105,
    width: 105,
    class: 'mr-[2px] right-0 top-[-7px]',
  },
  {
    color: 'text-[#539ED9]',
    title: 'Practice kindness',
    description: 'Do something kind for someone else.',
    maxWidth: 'max-w-[195px]',
    img: `${imageDomainUrl}/WellnessHub/practice-kindness.svg`,
    height: 107,
    width: 107,
    class: 'mr-[-2px] right-0 top-[-3px]',
  },
  {
    color: 'text-[#9AC17E]',
    title: 'Reflect on your day',
    description: 'Take time to review what went well today.',
    maxWidth: 'max-w-[170px]',
    img: `${imageDomainUrl}/WellnessHub/reflect-day.svg`,
    height: 119,
    width: 119,
    class: 'mt-[-4px] mr-[2px] right-0 top-[-11px]',
  },
  {
    color: 'text-[#D96D99]',
    title: 'Nurture your creativity',
    description:
      'Engage in creative activities whether drawing, writing, dancing, cooking, or singing.',
    maxWidth: 'max-w-[193px]',
    img: `${imageDomainUrl}/WellnessHub/nurture-creativity.svg`,
    height: 91,
    width: 91,
    class: 'mr-[8px] right-0 top-[4px]',
  },
];

// Export data
export { REMINDERS_CONTENTS };
