export const dailyPepTalkItems = [
  'Daily quiet reflection fosters self-honesty.',
  'Your past does not define your future.',
  'Patience brings timely opportunities.',
  'I deserve love and respect.',
  'My goals are within reach.',
  'I value my unique qualities.',
  'Strength and resilience define me.',
  'Gratitude enriches my daily life.',
  'I trust my decision-making abilities.',
  'Happiness and success are my birthright.',
  'Personal growth is my constant companion.',
  'I attract positivity and positive people.',
  'Confidence fuels my self-expression.',
  'I control my thoughts and emotions.',
  'Self-acceptance brings inner peace.',
  'Abundance surrounds my existence.',
  'Health and optimism energize me.',
  'Kindness radiates from within me.',
  'New possibilities excite my journey.',
  'Problem-solving is my strength.',
  'Positivity replaces negative thoughts.',
  'Miracles gravitate towards me.',
  'Life offers wonderful experiences.',
  'Believe in yourself; progress steadily.',
  'Challenges are growth opportunities.',
  'Setbacks pave way for comebacks.',
  'Stay focused on your path.',
  'Your capabilities are immense.',
  'Perseverance trumps perfection.',
  'Visualize success to drive action.',
  'Courage conquers limiting fears.',
  'Your potential knows no bounds.',
  'Challenges foster personal growth.',
  `Goals guide your life's direction.`,
  'Resilience is your superpower.',
  'Positive environments nurture success.',
  'Solutions outweigh problems.',
  'Setbacks are success stepping stones.',
  'Progress matters more than perfection.',
  'Purpose fuels lifelong passion.',
  'Balance work, play, and rest.',
  'Purpose drives passion forward.',
  'Boundaries create life balance.',
  'Life requires balanced pacing.',
  'Celebrate every small victory.',
  'Persistence overcomes obstacles.',
  'You control your destiny.',
  'Hard work yields rewards.',
  'Determination propels you forward.',
  'Stay focused on your dreams.',
];
