// const MEDITATIONS_LIST = [
//   {
//     title: 'Awaken Life Force',
//     genre: 'Meditate & Unwind',
//     audio: 'awaken-life-force.mp3',
//     duration: '11:37',
//     previewDuration: '00:44',
//     locked: false,
//   },
//   {
//     title: 'Be Unstoppable',
//     genre: 'Confidence Booster',
//     audio: 'be-unstoppable.mp3',
//     duration: '2:21',
//     previewDuration: '00:41',
//     locked: false,
//   },
//   {
//     title: 'Paris Awakening',
//     genre: 'Bedtime Stories',
//     audio: 'paris-awakening.mp3',
//     duration: '12:15',
//     previewDuration: '00:57',
//     locked: true,
//   },
//   {
//     title: 'Express Yourself',
//     genre: 'Journey to Happiness',
//     audio: 'express-yourself.mp3',
//     duration: '1:31',
//     previewDuration: '00:31',
//     locked: true,
//   },
//   {
//     title: 'Everything Benefits',
//     genre: 'Master Your Destiny',
//     audio: 'everything-benefits-you.mp3',
//     duration: '4:27',
//     previewDuration: '00:33',
//     locked: true,
//   },
//   {
//     title: 'The Growth Mindset',
//     genre: 'Tao of Living',
//     audio: 'the-growth-mindset.mp3',
//     duration: '2:56',
//     previewDuration: '00:40',
//     locked: true,
//   },
//   {
//     title: 'Know Your Value',
//     genre: 'Secrets to Life Balance',
//     audio: 'know-your-value.mp3',
//     duration: '3:23',
//     previewDuration: '00:36',
//     locked: true,
//   },
//   {
//     title: 'Keys to Balance',
//     genre: 'Master Your Destiny',
//     audio: 'keys-to-balance.mp3',
//     duration: '2:19',
//     previewDuration: '00:38',
//     locked: true,
//   },
//   {
//     title: 'Live with Intention',
//     genre: 'Journey to Happiness',
//     audio: 'live-with-intention.mp3',
//     duration: '3:31',
//     previewDuration: '00:41',
//     locked: true,
//   },
//   {
//     title: 'Path to Prosperity',
//     genre: 'Tao of Living',
//     audio: 'path-to-prosperity.mp3',
//     duration: '3:18',
//     previewDuration: '00:38',
//     locked: true,
//   },
//   {
//     title: 'Release the Past',
//     genre: 'Master Your Destiny',
//     audio: 'release-the-past.mp3',
//     duration: '3:13',
//     previewDuration: '00:33',
//     locked: true,
//   },
// ];

// export { MEDITATIONS_LIST };



const MEDITATIONS_LIST = [
  {
    title: 'Awaken Life Force',
    genre: 'Meditate & Unwind',
    audio: 'awaken-life-force.mp3',
    duration: '11:37',
    previewDuration: '00:44',
    locked: false,
  },
  {
    title: 'Be Unstoppable',
    genre: 'Confidence Booster',
    audio: 'be-unstoppable.mp3',
    duration: '2:21',
    previewDuration: '00:41',
    locked: false,
  },
  {
    title: 'Paris Awakening',
    genre: 'Bedtime Stories',
    audio: 'paris-awakening.mp3',
    duration: '12:15',
    previewDuration: '00:57',
    locked: false,
  },
  {
    title: 'Express Yourself',
    genre: 'Journey to Happiness',
    audio: 'express-yourself.mp3',
    duration: '1:31',
    previewDuration: '00:31',
    locked: false,
  },
  {
    title: 'Everything Benefits',
    genre: 'Master Your Destiny',
    audio: 'everything-benefits-you.mp3',
    duration: '4:27',
    previewDuration: '00:33',
    locked: false,
  },
  {
    title: 'The Growth Mindset',
    genre: 'Tao of Living',
    audio: 'the-growth-mindset.mp3',
    duration: '2:56',
    previewDuration: '00:40',
    locked: false,
  },
  {
    title: 'Know Your Value',
    genre: 'Secrets to Life Balance',
    audio: 'know-your-value.mp3',
    duration: '3:23',
    previewDuration: '00:36',
    locked: false,
  },
  {
    title: 'Keys to Balance',
    genre: 'Master Your Destiny',
    audio: 'keys-to-balance.mp3',
    duration: '2:19',
    previewDuration: '00:38',
    locked: false,
  },
  {
    title: 'Live with Intention',
    genre: 'Journey to Happiness',
    audio: 'live-with-intention.mp3',
    duration: '3:31',
    previewDuration: '00:41',
    locked: false,
  },
  {
    title: 'Path to Prosperity',
    genre: 'Tao of Living',
    audio: 'path-to-prosperity.mp3',
    duration: '3:18',
    previewDuration: '00:38',
    locked: false,
  },
  {
    title: 'Release the Past',
    genre: 'Master Your Destiny',
    audio: 'release-the-past.mp3',
    duration: '3:13',
    previewDuration: '00:33',
    locked: false,
  },
];

export { MEDITATIONS_LIST };
